# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -Wpedantic -Wconversion -Werror -g

# Source and object files
SRC = main.c \
      src/helpers/handle_error.c \
      src/shell/prompt.c \
      src/shell/shell.c \
      src/tokenizer/tokenizer.c \
      src/tokenizer/byte_type.c \
      libs/tiltyard/src/tiltyard_API.c \
      libs/tiltyard/src/tiltyard_Error.c

OBJ = $(SRC:.c=.o)
TARGET = ash

# Build target
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# Compile .c to .o (automatic dependency generation)
%.o: %.c
	$(CC) $(CFLAGS) -MMD -c $< -o $@

# Include dependency files generated by -MMD
-include $(OBJ:.o=.d)

# Clean object files, dependency files, and binary
clean:
	rm -f $(OBJ) $(OBJ:.o=.d)

